# New file
# See https://logging.apache.org/log4j/log4j-2.8/manual/configuration.html#Configuration_with_Properties
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %m%n

rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT

logger.hibernateSql.name = org.hibernate.SQL
logger.hibernateSql.level = debug

logger.hibernateType.name = org.hibernate.type
logger.hibernateType.level = trace

logger.hibernateJdbcBind.name = org.hibernate.orm.jdbc.bind
logger.hibernateJdbcBind.level = trace

logger.hibernateJdbcExtract.name = org.hibernate.orm.jdbc.extract
logger.hibernateJdbcExtract.level = trace